---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: loopback
      ios_l3_interface:
        name: loop{{ item.name }}
        ipv4: "{{ item.ipv4 }}"
        state: present
      with_items:
        - { name: 5, ipv4: "192.168.5.1/24" }
        - { name: 6, ipv4: "192.168.6.1/24" }
        - { name: 7, ipv4: "192.168.7.1/24" }

    - name: Show Int
      ios_command:
        commands:
          - show ip int br
      register: show

    - debug: var=show.stdout_lines
