---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Show Int
      ios_command:
        commands:
          - show ip int br
      register: show

    - debug: var=show.stdout_lines
