---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
     - name: loopback
       ios_l3_interface:
          name: loop {{ item.na }}
          ipv4: "{{ item.ip }}"
       with_items:
         - { na: 5, ip: "192.168.5.1/24" }
         - { na: 6, ip: "192.168.6.1/24" }
         - { na: 7, ip: "192.168.7.1/24" }
     - name: Show Int
       ios_command:
         commands:
           - show ip int br
       register: show

     - debug: var=show.stdout_lines
