Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> ---
SyntaxError: invalid syntax
>>> ---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: loopback
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        state: present
      with_items:
        - { name: "loopback5", ipv4: 192.168.5.1 }
        - { name: "loopback6", ipv4: 192.168.6.1 }
        - { name: "loopback7", ipv4: 192.168.7.1 }

    - name: Show Int
      ios_command:
        commands:
          - show ip int br
      register: show

    - debug: var=show.stdout_lines